nysfAXF/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^home/', views.home,name='home'),

    url(r'^market/', views.market,name='market'),
    url(r'^market_param/(\d+)/(\d+)/(\d+)/', views.market_param,name='market_param'),


    url(r'^cart/', views.cart,name='cart'),
    url(r'^mine/', views.mine,name='mine'),


#     登录注册
    url(r'^register/',views.register,name='register'),
#     验证用户名是否存在
    url(r'^checkuser/',views.check_user),
#     登录
    url(r'^login/',views.login,name='login'),
    url(r'^check_username/',views.check_username),
    url(r'^login_out/',views.login_out,name='login_out'),


    # 添加商品
    url(r'^addgoods/',views.add_goods,name='addgoods'),
    url(r'^subgoods/',views.sub_goods,name='subgoods'),

#     购物车添加商品
    url(r'^addshops/',views.add_shops,name='addshops'),
    url(r'^subshops/',views.sub_shops,name='subshops'),
]

nysfAXF/nysfAXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app'))
]

nysfAXF/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    {% block extCSS %}
    
    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    {% block extJS %}

    {% endblock %}
</body>
</html>

nysfAXF/templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}


{% block footer %}
    <footer>
        <a href="{% url 'app:home' %}" class="home">
            <dl>
                <dt>
                    <span>
                    </span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>


        <a href="{% url 'app:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>


        <a href="{% url 'app:cart' %}" class="cart">
            <dl>
                <dt>
                <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>


        <a href="{% url 'app:mine' %}" class="mine1">
            <dl>
                <dt>
                <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>

    </footer>
{% endblock %}

nysfAXF/templates/cart.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="../static/app/cart/css/cart.css">
{% endblock %}

{% block content %}
    <div id="cart">
        <h3>
            购物车
        </h3>

        <div class="full">
            <section>
                <ul>
                    <li>
                        <div class="clear">
                            <p class="infoJustify">
                                收货人
                            </p>
                            <p>
                                <span>
                                    胡冠雨
                                </span>
                            </p>
                        </div>
                    </li>
                    <li>
                        <div class="clear">
                            <p class="infoJustify">
                                电话
                            </p>
                            <p>
                                <span>
                                    110
                                </span>
                                <a class="change" href="">修改></a>
                            </p>
                        </div>
                    </li>
                    <li>
                        <div class="clear">
                            <p class="infoJustify">
                                收货地址
                            </p>
                            <p>
                                <span>
                                    南阳师范学院西区实训楼3号楼317
                                </span>
                            </p>
                        </div>
                    </li>
                </ul>
                <div class="bill">
                    <p>
                        闪送超市
                    </p>
                    <a href="">
                        凑单专区
                    </a>
                    <p>
                        ¥0起送,22:00前满¥30免运费
                    </p>
                </div>
                <div class="delivery">
                    <span>收货时间</span>
                    <span>一小时送达</span>
                    <a href="">可预订></a>
                </div>
                <div class="delivery">
                    <span>收货备注</span>
                    <input type="text" placeholder="可输入你的特殊服务要求 我们尽量满足 美女没有 帅哥一堆">
                </div>
            </section>

            <menu>
                <ul>
                    {% for cart in carts %}

                        <li class="menuList">
                            <div class="confirm">
                                    <span class="is_choosed">
                                        <span></span>
                                    </span>
                            </div>
                            <a href="#">
                                <img src="" alt="">
                                <p>{{ cart.gname }}</p>
                            </a>
                            <section>
                                <button id="{{ cart.id }}" class="subshop">-</button>
                                    <span>{{ cart.gnum }}</span>
                                <button id="{{ cart.id }}"  class="addshop">+</button>
                            </section>
                        </li>
                    {% endfor %}

                    <li class="payTheBill">
                        <div class="confirm">
                                <span class="all_select">
                                    <span>√</span>
                                </span>
                        </div>
                        <p>
                            <span>全选</span>
                            <span>总价:</span>
                        </p>
                        <span id="getorder">下单</span>
                    </li>

                </ul>

            </menu>
        </div>
    </div>
{% endblock %}

{% block extJS %}
     <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
{% endblock %}

nysfAXF/templates/error.html
<h2>账号或者密码不存在,请重新登录</h2>
<a href="{% url 'app:login' %}"></a>

nysfAXF/templates/home.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="../static/app/home/css/home.css">
{% endblock %}

{% block content %}
    <div id="home">

        {#  此处为轮播图  #}
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for wheel in wheels %}
                    <div class="swiper-slide">
                        <a href="#">
                            <img src="{{ wheel.img }}" alt="{{ wheel.name }}">
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        {#  此处为顶部菜单      #}
        <div class="topMenu">
            <nav>
                <ul>
                    {% for nav in navs %}
                        <li>
                            <img src="{{ nav.img }}" alt="{{ nav.name }}">
                            <span>{{ nav.name }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>

        {#  菜单轮播图   #}
        <div class="swiper-container" id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for mustbuy in mustbuys %}
                    <li class="swiper-slide">
                        <img src="{{ mustbuy.img }}" alt="{{ mustbuy.name }}">
                    </li>
                {% endfor %}
            </ul>
        </div>

        {#   商品选购     #}
        <div class="CVS">
            <h2>
                <img src="{{ shops.0.img }}" alt="{{ shops.0.name }}">
            </h2>
            <fieldset>
                <a href="#">
                    <img src="{{ shops.1.img }}" alt="{{ shops.1.name }}">
                </a>
                <a href="#">
                    <img src="{{ shops.2.img }}" alt="{{ shops.2.name }}">
                </a>
            </fieldset>

            <ul>
                {% for shop in shops3_7 %}
                    <li>
                        <img src="{{ shop.img }}" alt="{{ shop.name }}">
                        <span>{{ shop.name }}</span>
                    </li>
                {% endfor %}
            </ul>

            <ol>
                {% for shop in shops7_ %}
                    <li>
                        <a href="">
                            <img src="{{ shop.img }}" alt="{{ shop.name }}">
                        </a>
                    </li>
                {% endfor %}
            </ol>

            <div class="mainInfo">

                {% for mainshow in mainshows %}
                    <section>
                        <h3>
                            <p>{{ mainshow.name }}</p>
                            <a href="">更多></a>
                            <span></span>
                        </h3>
                        <div>
                            <a href="">
                                <img src="{{ mainshow.img }}" alt="">
                            </a>
                        </div>
                        <ul>
                            <li>
                                <a href="">
                                    <img src="{{ mainshow.img1 }}" alt="">
                                    <span class="description">{{ mainshow.longname1 }}</span>
                                    <span>¥{{ mainshow.price1 }}</span>
                                    <s>¥{{ mainshow.marketprice1 }}</s>
                                </a>
                                <button>
                                    <span>
                                        &#43;
                                    </span>
                                </button>
                            </li>
                            <li>
                                <a href="">
                                    <img src="{{ mainshow.img2 }}" alt="">
                                    <span class="description">{{ mainshow.longname2 }}</span>
                                    <span>¥{{ mainshow.price2 }}</span>
                                    <s>¥{{ mainshow.marketprice2 }}</s>
                                </a>
                                <button>
                                    <span>
                                        &#43;
                                    </span>
                                </button>
                            </li>
                            <li>
                                <a href="">
                                    <img src="{{ mainshow.img3 }}" alt="">
                                    <span class="description">{{ mainshow.longname3 }}</span>
                                    <span>¥{{ mainshow.price3 }}</span>
                                    <s>¥{{ mainshow.marketprice3 }}</s>
                                </a>
                                <button>
                                    <span>
                                        &#43;
                                    </span>
                                </button>
                            </li>
                        </ul>

                    </section>
                {% endfor %}


            </div>
        </div>
    </div>
{% endblock %}

{% block extJS %}
    <script type="text/javascript" src="../static/app/home/js/home.js"></script>
{% endblock %}

nysfAXF/templates/market.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/css/market.css' %}">
{% endblock %}

{% block content %}
    <div id="market">
        {#  侧面菜单栏  #}
        <aside>
            <ul>
                {% for foo in foodtypes %}
                    <li>
                        <a href="{% url 'app:market_param' foo.typeid 0 1 %}">{{ foo.typename }}</a>
                        {% ifequal foo.typeid typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
        </aside>
        {#  右面商品栏  #}
        <section>
            <nav>
                <ul>
                    <li id="alltypes">
                        <span >全部分类<span id="typesdown" class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span></span>
                    </li>
                    <li id="allsort">
                        <span>综合排序<span id="sortdown"  class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span></span>
                    </li>
                </ul>
            </nav>

            <menu>
                <ul>
                    {% for good in goods %}
                        <li>
                            <a href="">
                                <img src="{{ good.productimg }}" alt="">
                                <span class="shoppingInfo">
                                    <h6>{{ good.productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>
                                            精选
                                        </span>
                                        <span>

                                        </span>
                                    </p>
                                    <span class="unit">{{ good.specifics }}</span>
                                    <p class="price">
                                        <span>
                                            ¥{{ good.price }}
                                        </span>
                                        <s>¥{{ good.marketprice }}</s>
                                    </p>

                                </span>
                            </a>
                            <section>
                                <button id="{{ good.id }}" class="subgood">-</button>
                                <span>0</span>
                                <button id="{{ good.id }}" class="addgood">+</button>
                            </section>
                        </li>

                    {% endfor %}
                </ul>

                <div id="goodscontainer" style="display: none">
                    <div>
                        {% for name in names %}
                            <a href="{% url 'app:market_param' typeid name.1 1 %}">
                                <span>
                                    {{ name.0 }}
                                </span>
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div id="sort" style="display: none">
                    <div>
                        <a href="{% url 'app:market_param' typeid cid 1 %}">
                            <span>
                                综合排序
                            </span>
                        </a>
                        <a href="{% url 'app:market_param' typeid cid 2 %}">
                            <span>
                                销量排序
                            </span>
                        </a>
                        <a href="{% url 'app:market_param' typeid cid 3 %}">
                            <span>
                                价格升序
                            </span>
                        </a>
                        <a href="{% url 'app:market_param' typeid cid 4 %}">
                            <span>
                                价格降序
                            </span>
                        </a>
                    </div>
                </div>
            </menu>
        </section>
    </div>
{% endblock %}
{% block extJS %}
    <script type="text/javascript" src="{% static 'app/market/js/market.js' %}"></script>
{% endblock %}

nysfAXF/templates/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="../static/app/mine/css/mine.css">
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">

            {% if is_login %}
                <img src="{{ icon }}" alt="头像">
            {% else %}
                 <span class="glyphicon glyphicon-user"></span>
            {% endif %}

            {% if is_login %}
                <p>{{ username }}</p>
            {% else %}
                 <p>
                     <a href="{% url 'app:login' %}">未登录</a>
                 </p>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>
                    等级
                </span>
            </p>
            {% if is_login %}

            {% else %}
                <a id="regis" href="{% url 'app:register' %}">注册</a>
            {% endif %}


            <p>
                <span class="glyphicon glyphicon-heart">
                    商品收藏
                </span>
            </p>

        </div>

        <div class="mine">
            <p><span>我的订单<a href="">查询全部订单&gt;</a></span></p>
             <div id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt>
                                    <span class="glyphicon glyphicon-usd"></span>
                            <dd>
                                代付款
                            </dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                    <span class="glyphicon glyphicon-envelope">

                                    </span>
                            <dd>
                                代付款
                            </dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                    <span class="glyphicon glyphicon-pencil">

                                    </span>
                            <dd>
                                代付款
                            </dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                    <span class="glyphicon glyphicon-retweet">

                                    </span>
                            <dd>
                                代付款
                            </dd>
                            </dt>
                        </dl>
                    </li>
                </ul>
            </div>
            <menu>
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-import"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p><a href="{% url 'app:login_out' %}">退出当前账号</a></p>
            {% endif %}
        </div>

    </div>
{% endblock %}