axf_test/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^home/',views.home,name='home'),
    url(r'^market/',views.market,name='market'),
    url(r'^market_param/(\d+)/(\d+)/(\d+)/',views.market_param,name='marketparam'),
    url(r'^cart/',views.cart,name='cart'),
    url(r'^mine/',views.mine,name='mine'),
    url(r'^register/',views.register,name='register'),
    url(r'^checkuser/',views.check_user,name='check_user'),
    url(r'^login/',views.login,name='login'),
    url(r'^check/',views.check,name='check'),
    url(r'^loginout',views.loginout,name='loginout'),
    url(r'^addgoods/',views.addgoods,name='addgoods'),
    url(r'^subgoods/',views.subgoods,name='subgoods'),
    url(r'^addshop/',views.addshop,name='addshop'),
    url(r'^subshop/',views.subshop,name='subshop'),
    url(r'^change_choose_statu/', views.changechoosestatu),
    url(r'^all_select/', views.changeallstatu,name='all_select'),
    url(r'^goodsinfo/', views.orderinfo),
    url(r'^dingdan/$', views.order),
]

axf_test/axf_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls',namespace='app')),
]

axf_test/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    {% block extCSS %}

    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}
    {% block content %}

    {% endblock %}
    {% block footer %}

    {% endblock %}
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    {% block extJS %}

    {% endblock %}
</body>
</html>

axf_test/templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'app:home' %}" class="home">
            <dl>
                <dt>

                    <span>

                    </span>
                <dd>首页</dd>
                </dt>

            </dl>
        </a>


        <a href="{% url 'app:market' %}" class="market">
        <dl>
            <dt>
                <span>

                </span>
            <dd>闪购</dd>
            </dt>

        </dl>
        </a>
        <a href="{% url 'app:cart' %}" class="cart">
        <dl>
            <dt>
                <span>

                </span>
            <dd>购物车</dd>
            </dt>

        </dl>
        </a>
        <a href="{% url 'app:mine' %}" class="mine1">
        <dl>
            <dt>
                <span>

                </span>
            <dd>我的</dd>
            </dt>

        </dl>
        </a>
    </footer>

{% endblock %}

axf_test/templates/cart.html
{% extends 'base_main.html' %}
{% load  static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/css/cart.css' %}">
{% endblock %}

{% block content %}
    <div id="cart">
        <div class="cart">
            <h3><b>购物车</b></h3>
            <section class="full">
                <section>
                    <ul>
                        <li>
                            <div class="clear">
                                <p class="infoJustify">
                                    收货人
                                    <b></b>
                                </p>
                                <p>
                                    :
                                    <span>ROCK</span>
                                </p>
                            </div>
                        </li>
                        <li>
                            <div class="clear">
                                <p class="infoJustify">
                                    电话
                                    <b></b>
                                </p>
                                <p>
                                    :
                                    <span>110</span>
                                    <a href="" class="change">修改></a>
                                </p>
                            </div>
                        </li>
                        <li>
                            <div class="clear">
                                <p class="infoJustify">
                                    收货地址
                                    <b></b>
                                </p>
                                <p>
                                    :
                                    <span>河南省南阳市卧龙区</span>
                                </p>
                            </div>
                        </li>
                    </ul>

                    <section class="bill">
                        <p>闪送超市</p>
                        <p>0元起送,22:00前免30运费</p>
                        <a href="">凑单专区</a>
                    </section>
                    <section class="delivery">
                        <span>收货时间</span>
                        <span>一小时送达</span>
                        <a href="">可预订></a>
                    </section>
                    <section class="delivery">
                        <span>收货备注</span>
                        <input type="text" placeholder="可输入100字以内特殊要求">
                    </section>
                    <menu>
                        <ul>
                            {% for cart in carts %}
                                <li class="menuList" id="{{ cart.id }}">
                                    <div class="confirm">
                                        <span class="is_choosed" ></span>

                                    </div>
                                    <a href="#">
                                        <img src="{{ cart.goodid.productimg }}" alt="{{ cart.goodid.productname }}">
                                        <p>{{ cart.goodid.productlongname }}</p>
                                    </a>
                                    <section>
                                        <button class="subshop">-</button>
                                        <span>{{ cart.gnum }}</span>
                                        <button class="addshop">+</button>
                                    </section>
                                </li>
                            {% endfor %}

                            <li class="payTheBill">
                                <div class="confirm">
                                <span class="all_select">
                                </span>
                                </div>
                                <p>
                                    <span>全选</span>
                                    <span>总价:</span>

                                </p>
                                <span id="getorder">下单</span>
                            </li>

                        </ul>
                    </menu>
                </section>
            </section>
        </div>

    </div>
{% endblock %}
{% block extJS %}
    <script type="text/javascript" src="{% static 'app/cart/js/yy.js' %}"></script>
{% endblock %}

axf_test/templates/home.html
{% extends 'base_main.html' %}
{% load  static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="../static/app/home/css/home.css">
{% endblock %}

{% block content %}
    <div id="home">

        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for wheel in wheels %}
                    <div class="swiper-slide">
                        <a href="#">
                            <img src="{{ wheel.img }}" alt="{{ wheel.name }}">
                        </a>
                    </div>
                {% endfor %}
            </div>
            <!-- 如果需要滚动条 -->
            <div class="swiper-pagination"></div>
        </div>

        <div class="topMenu">
            <nav>
                <ul>
                    {% for nav in navs %}
                        <li><img src="{{ nav.img }}" alt="{{ nav.name }}">
                            <span>{{ nav.name }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </nav>

        </div>


        <div class="swiper-container" id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for must in mustbuy %}
                    <li>
                        <a href="">
                            <img src="{{ must.img }}" alt="{{ must.name }}">
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="CVS">
            <h2>
                <img src="{{ shop1.img }}" alt="">
            </h2>
            <fieldset>
                {% for shop in shop2 %}
                    <a href="">
                        <img src="{{ shop.img }}" alt="">
                    </a>
                {% endfor %}
            </fieldset>
            <ul>
                {% for s in shop3 %}
                    <li>
                        <img src="{{ s.img }}" alt="">
                        <span>{{ s.name }}</span>
                    </li>
                {% endfor %}


            </ul>
            <ol>
                {% for foo in shop4 %}
                    <li>
                        <a href="">
                            <img src="{{ foo.img }}" alt="">
                        </a>
                    </li>
                {% endfor %}
            </ol>
        </div>

        <div class="mainInfo">
            {% for main in mainshow %}
                <section>
                    <h3>
                        {{ main.name }}
                        <a href="">更多></a>
                        <span></span>
                    </h3>
                    <div>
                        <a href="">
                            <img src="{{ main.img }}" alt="">
                        </a>
                    </div>
                        <ul>
                            <li>
                                <a href="">
                                    <img src="{{ main.img1 }}" alt="">
                                    <span class="description">{{ main.longname1 }}</span>
                                    <span>¥{{ main.price1 }}</span>
                                    <s>{{main.marketprice1  }}</s>
                                </a>
                                <button>
                                    <span>+</span>
                                </button>
                            </li>
                            <li>
                                <a href="">
                                    <img src="{{ main.img2 }}" alt="">
                                    <span class="description">{{ main.longname2 }}</span>
                                    <span>¥{{ main.price2 }}</span>
                                    <s>{{ main.marketprice2 }}</s>
                                </a>
                                <button>
                                    <span>+</span>
                                </button>
                            </li>
                            <li>
                                <a href="">
                                    <img src="{{ main.img3 }}" alt="">
                                    <span class="description">{{ main.longname3}}</span>
                                    <span>¥{{ main.price3 }}</span>
                                    <s>{{ main.marketprice3 }}</s>
                                </a>
                                <button>
                                    <span>+</span>
                                </button>
                            </li>
                        </ul>

                </section>
            {% endfor %}
        </div>

    </div>

{% endblock %}
{% block extJS %}
    <script type="text/javascript" src="../static/app/home/js/home.js"></script>
{% endblock %}

axf_test/templates/market.html
{% extends 'base_main.html' %}
{% load  static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/css/market.css' %}">
{% endblock %}
{% block content %}
    <div id="market">
        {#        左边导航#}
        <aside>
            <ul>
                {% for food in foodtypes %}
                    <li>
                        <a href="{% url 'app:marketparam' food.typeid 0 1 %}">{{ food.typename }}</a>
                        {% ifequal food.typeid typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
        </aside>
        {#        右边商品#}
        <section>
            <nav>
                <ul>
                    <li id="alltypes"><span>全部类型<span id="typedown" class="glyphicon glyphicon-chevron-down"
                                                      style="font-weight: 100"></span></span></li>
                    <li id="allsort"><span>综合排序<span id="sortdown" class="glyphicon glyphicon-chevron-down"
                                                     style="font-weight: 100"></span></span></li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for good in goods %}
                        <li>
                            <a href="">
                                <img src="{{ good.productimg }}" alt="">
                                <artile class="shoppingInfo">
                                    <h6>{{ good.productname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </p>
                                    <span class="unit">{{ good.specifics }}</span>
                                    <p class="price">
                                        <span>¥{{ good.price }}</span>
                                        <s><span>¥{{ good.marketprice }}</span></s>
                                    </p>
                                </artile>
                            </a>
                            <section>
                                <button id="{{ good.id }}" class="subgood">-</button>
                                <span>0</span>
                                <button id="{{ good.id }}" class="addgood">+</button>
                            </section>
                        </li>
                    {% endfor %}
                </ul>
                <div id="goodscontainer" style="display: none">
                    <div id="alltypes">
                        {% for name in names %}
                            <a href="{% url 'app:marketparam' typeid name.1 1 %}"><span>{{ name.0 }}</span></a>
                        {% endfor %}
                    </div>
                </div>
                <div id="sort" style="display: none">
                    <div>
                        <a href="{% url 'app:marketparam' typeid cid 1 %}" class="sorta"><span>综合排序</span></a>
                        <a href="{% url 'app:marketparam' typeid cid 2 %}" class="sorta"><span>销量排序</span></a>
                        <a href="{% url 'app:marketparam' typeid cid 3 %}" class="sorta"><span>价格最低</span></a>
                        <a href="{% url 'app:marketparam' typeid cid 4 %}" class="sorta"><span>价格最高</span></a>
                    </div>
                </div>
            </menu>
        </section>


    </div>
{% endblock %}
{% block extJS %}
    <script type="text/javascript" src="{% static 'app/market/js/market.js' %}"></script>
{% endblock %}

axf_test/templates/mine.html
{% extends 'base_main.html' %}
{% load  static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/css/mine.css' %}">
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">

            {% if is_login %}
                <span><img src="{{ icon }}" alt="头像" style="width:65px;height:65px;border-radius:50px"></span>
            {% else %}
                 <span class="glyphicon glyphicon-user"></span>
            {% endif %}

            {% if is_login %}
                <p>{{ username }}</p>
            {% else %}
                 <p>
                     <a href="{% url 'app:login' %}">未登录</a>
                 </p>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>
                    等级
                </span>
            </p>
            {% if is_login %}

            {% else %}
                <a id="regis" href="{% url 'app:register' %}">注册</a>
            {% endif %}


            <p>
                <span class="glyphicon glyphicon-heart">
                    商品收藏
                </span>
            </p>

        </div>
        <section class="mine">
            <p>
                <span>我的订单
                    <a href="{% url 'app:cart'%}">全部订单>></a>
                </span>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-usd"></span></dt>
                                <dd>代付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-envelope"></span></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-import"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </menu>
            <p>
                {% if is_login %}
                    <a href="{% url 'app:loginout' %}">退出当前账号</a>
                {% endif %}

            </p>
        </section>


    </div>
{% endblock %}