test8_zhongjianjian_uploadimg/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^qiang/',views.qiang,name='qiang'),
    url(r'^upload/',views.upload,name='upload'),
    url(r'^show/',views.show,name='show'),
    url(r'^hh/',views.hh,name='hh')

]

test8_zhongjianjian_uploadimg/test8/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^app/',include('app.urls',namespace='app'))
]

test8_zhongjianjian_uploadimg/app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name=models.CharField(max_length=15)
    icon=models.FileField(upload_to='upload')

test8_zhongjianjian_uploadimg/app/views.py
import random

from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
from app.models import User
from test8 import settings


def qiang(request):
    r = random.randrange(100)
    if r > 90:
        return HttpResponse('恭喜你抢到优惠券')
    else:
        return HttpResponse('很遗憾没有抢到')


def upload(request):
    if request.method == 'GET':
        return render(request, 'upload.html')
    else:
        image = request.FILES.get('icon')
        name=request.POST.get('name')
        user = User()
        user.name=name
        user.icon=image
        user.save()
        return HttpResponse('图片上传成功')


def show(request):

    user=User.objects.all().first()
    imgurl='timg.jpeg'
    context={
        'imgurl':imgurl
    }
    return render(request,'show.html',context=context)

test8_zhongjianjian_uploadimg/templates/show.html
<img src="{{ imgurl }}" alt="头像">

test8_zhongjianjian_uploadimg/templates/upload.html
<form action="{% url 'app:upload' %}" method="post" enctype="multipart/form-data">
    <span>用户名</span><input type="text" name="name" placeholder="请输入用户名">
    <br>
    <span>头像</span><input type="file" name="icon">
    <br>
    <input type="submit" value="上传">
</form>